<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class maintenance extends Model {
    use HasFactory;

    public function toArray(bool $extends = true) : array {
        if ($extends) {
            $model = parent::toArray();

            $model['date'] = date('Y.m.d',strtotime($model['date']));

            return $model;
        } else {
            return parent::toArray(); // TODO: Change the autogenerated stub
        }
    }

}
